sudo: required

language: node_js
nodejs:
  - "6"
  - "8"
  - "9"
  - "node"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
      addons:
        chrome: stable
      script: npm run test-headless
    - stage: Deploy
      env:
        - name="Github Pages"
      node_js:
        - "node"
      script:
        - npm run build-gh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist-gh
        on:
          branch:
            - master
            - develop
    - env:
        - name="Firebase & Netlify"
      script:
        - npm run build
      after_success:
        - npm run deploy-firebase
        - npm run deploy-netlify