language: node_js
node_js:
  - "6.9"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - test-cache

script:
  - npm run build-gh
  - npm run build

after_success:
  - npm run deploy-firebase
  - npm run deploy-gh

notifications:
  email:
    on_failure: change
    on_success: change