language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - test-angular-cli-ghpages

script:
  - npm run build-gh
  - npm run build

after_success:
  - npm run firebase deploy --token $FIREBASE_TOKEN
  - npm run angular-cli-ghpages --dir dist-gh --repo=https://GH_TOKEN@github.com/ELC/hello-angular.git --message="Update Website"

notifications:
  email:
    on_failure: change
    on_success: change