sudo: required

language: node_js
node_js: "node"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

stages:
  - name: test
  - name: build
  - name: deploy-test
    if: branch = develop
  - name: deploy
    if: branch = master

install:
  - npm set progress=false
  - npm install

jobs:
  include:
    - stage: test
      node_js: "6"
      addons:
        chrome: stable
      script: npm run test-headless
    - node_js: "8"
      addons:
        chrome: stable
      script: npm run test-headless
    - addons:
        chrome: stable
      script: npm run test-headless
    - stage: build
      script:
        - npm run build
    - stage: deploy-test
      env:
        - name=Netlify Testing
      install:
        - npm set progress=false
        - npm install -g netlify-cli
      script:
        - npm run clone
        - npm run clean
        - npm run deploy-netlify-test
    - stage: deploy
      install: true
      env:
        - name=Github Pages
      script:
        - npm run clone
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist
    - env:
        - name=Firebase & Netlify
      install:
        - npm set progress=false
        - npm install -g firebase-tools netlify-cli
      script:
        - npm run clone
        - npm run clean
        - npm run deploy-firebase
        - npm run deploy-netlify-production