sudo: required

language: node_js
node_js: "node"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
      node_js: "6"
      addons:
        chrome: stable
      script: npm run test-headless
    - node_js: "8"
      addons:
        chrome: stable
      script: npm run test-headless
    - addons:
        chrome: stable
      script: npm run test-headless
    - stage: Build
      script:
        - npm run build-gh
        - cd dist-gh
        - ../publish.sh build-gh
    - stage: Deploy
      if: branch = master
      install: true
      env:
        - name=Github Pages
      script:
        - git clone -b build-gh https://github.com/ELC/hello-angular.git
        - mv hello-angular dist-gh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist-gh
    - env:
        - name=Firebase & Netlify
      install:
        - npm install -g firebase-tools netlify-cli
      script:
        - git clone -b build-gh https://github.com/ELC/hello-angular.git
        - mv hello-angular dist
        - sed -i -e 's/https:\/\/elc.github.io\/hello-angular\///g' dist/index.html
        - firebase deploy --token $FIREBASE_TOKEN
        - netlify deploy -t $NETLIFY_TOKEN -p dist -s xenodochial-davinci-fc66ee