sudo: required

language: node_js

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: Test
      node_js:
        - "6"
        - "8"
        - "9"
        - "node"
      addons:
        chrome: stable
      cache:
        directories:
          - node_modules
      script: npm run test-headless
    - stage: Build
      node_js:
          - "node"
      script:
        - npm run build-gh
        - npm run build
    - stage: Deploy to production
      node_js:
        - "node"
      install:
        - npm install
      script:
        - npm run deploy-firebase
        - npm run deploy-netlify
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist-gh
        on:
          branch:
            - master
            - develop