sudo: required

language: node_js
node_js: "node"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules

addons:
  chrome: stable

jobs:
  include:
    - stage: Test
      node_js: "6"
      script: npm run test-headless
    - node_js: "8"
      script: npm run test-headless
    - node_js: "9"
      script: npm run test-headless
    - script: npm run test-headless
    - stage: Deploy
      env:
        - name="Github Pages"
      script:
        - npm run build-gh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist-gh
        on:
          branch:
            - master
            - develop
    - env:
        - name="Firebase & Netlify"
      script:
        - npm run build
      after_success:
        - npm run deploy-firebase
        - npm run deploy-netlify