sudo: required

language: node_js
node_js: "node"

branches:
  only:
    - master
    - develop

cache:
  directories:
    - node_modules
    - dist_gh

stages:
  - name: test
  - name: build
    if: branch = master OR branch = develop
  - name: deploy-test
    if: branch = develop
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      node_js: "6"
      addons:
        chrome: stable
      script: npm run test-headless
    - node_js: "8"
      addons:
        chrome: stable
      script: npm run test-headless
    - addons:
        chrome: stable
      script: npm run test-headless
    - stage: build
      script:
        - npm run build-gh
    - stage: deploy-test
      env:
        - name=Netlify Testing
      install:
        - npm install -g firebase-tools netlify-cli
      script:
        - mv dist_gh dist
        - sed -i -e 's/https:\/\/elc.github.io\/hello-angular\///g' dist/index.html
        - netlify deploy -t $NETLIFY_TOKEN -p dist -s focused-dubinsky-dee263
    - stage: deploy
      install: true
      env:
        - name=Github Pages
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: dist_gh
    - env:
        - name=Firebase & Netlify
      install:
        - npm install -g firebase-tools netlify-cli
      script:
        - mv dist_gh dist
        - sed -i -e 's/https:\/\/elc.github.io\/hello-angular\///g' dist/index.html
        - firebase deploy --token $FIREBASE_TOKEN
        - netlify deploy -t $NETLIFY_TOKEN -p dist -s xenodochial-davinci-fc66ee