language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - test-angular-cli-ghpages

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod
  - ng build --prod --output-path dist-gh --base-href "https://elc.github.io/hello-angular/"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - angular-cli-ghpages --dir dist-gh --repo=https://GH_TOKEN@github.com/ELC/hello-angular.git --message="Update Website"

notifications:
  email:
    on_failure: change
    on_success: change